sfcy/company/urls.py
# company/urls.py
from django.urls import path
from .views import CompanyCreateView, VerifyUserMappingView, user_mapping, company_dashboard, CompanyFilesView, access_denied

urlpatterns = [
    path('create/', CompanyCreateView.as_view(), name='company_create'),
    path('user_mapping/', user_mapping, name='user_mapping'),
    path('verify_user_mapping/<int:mapping_id>/<str:verification_token>/', VerifyUserMappingView.as_view(), name='verify_user_mapping'),
    path('company_dashboard/<int:company_id>/', company_dashboard, name='company_dashboard'),
    path('<int:company_id>/files/', CompanyFilesView.as_view(), name='company_files'),
    path('access-denied/', access_denied, name='access_denied'),

]

sfcy/sfcy/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView
from django.urls import path, reverse_lazy
from .views import profile
from allauth.account.views import LogoutView
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('accounts/', include('allauth.account.urls')),
    path('', RedirectView.as_view(url=reverse_lazy('account_login')), name='home_redirect'),
    path('accounts/profile/', profile, name='account_profile'),
    path('company/', include('company.urls')),
    path('accounts/logout/', LogoutView.as_view(), name='account_logout'),
    path('twilio/', include('twilio_integration.urls')),
]

sfcy/company/models.py
# company/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils.crypto import get_random_string
import os
from datetime import datetime

class WhatsAppNumber(models.Model):
    number = models.CharField(max_length=15)
    companies = models.ManyToManyField('Company', related_name='whatsapp_numbers')

    def __str__(self):
        return self.number

class Company(models.Model):
    name = models.CharField(max_length=255)
    pan_number = models.CharField(max_length=10, unique=True, error_messages={'unique': 'This PAN is already in use.'})
    address = models.TextField()
    city = models.CharField(max_length=100)
    pincode = models.CharField(max_length=10)
    email = models.EmailField()
    is_approved = models.BooleanField(default=False)
    confirmation_token = models.CharField(max_length=32, blank=True, null=True)
    whatsapp_number = models.CharField(max_length=10)

    def generate_confirmation_token(self):
        return get_random_string(length=32)

    def save(self, *args, **kwargs):
        if not self.confirmation_token:
            self.confirmation_token = self.generate_confirmation_token()
        super().save(*args, **kwargs)

    def __str__(self):
        return self.name

class UserCompanyMapping(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    company = models.ForeignKey(Company, on_delete=models.CASCADE)
    is_user_verified = models.BooleanField(default=False)  # New field for user verification
    is_approved = models.BooleanField(default=True)
    verification_token = models.CharField(max_length=255, null=True, blank=True)

    def __str__(self):
        return f"{self.user.username} - {self.company.name}"

class Year(models.Model):
    year = models.IntegerField(unique=True)

    def __str__(self):
        return str(self.year)


class Month(models.Model):
    month = models.CharField(max_length=255, unique=True)

    def __str__(self):
        return self.month


class Department(models.Model):
    name = models.CharField(max_length=255, unique=True)
    show_field = models.BooleanField(default=True)  # Added BooleanField

    def __str__(self):
        return self.name


class ReportName(models.Model):
    name = models.CharField(max_length=255)
    department = models.ForeignKey(Department, on_delete=models.CASCADE)
    show_field = models.BooleanField(default=True)  # Added BooleanField

    def __str__(self):
        return f"{self.name} - {self.department}"



class FileUpload(models.Model):

    def dynamic_upload_path(self, filename):
        timestamp = datetime.now().strftime("%Y%m%d%H%M%S")
        return f'uploads/{self.company_id}/{self.department}/{self.year}/{self.month}/{str(self.reports_name)}/{timestamp}_{filename}'

    company = models.ForeignKey(Company, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    department = models.ForeignKey(Department, on_delete=models.CASCADE)
    month = models.ForeignKey(Month, on_delete=models.CASCADE)
    year = models.ForeignKey(Year, on_delete=models.CASCADE)
    reports_name = models.ForeignKey(ReportName, on_delete=models.CASCADE)
    file = models.FileField(upload_to=dynamic_upload_path)
    upload_date = models.DateField(auto_now_add=True)
    file_name = models.CharField(max_length=255)  # taken from uploaded file name
    description = models.TextField()
    show_field = models.BooleanField(default=True)
    is_verified = models.BooleanField(default=False)
    extra_field1 = models.CharField(max_length=255, blank=True, null=True)
    extra_field2 = models.CharField(max_length=255, blank=True, null=True)

    def __str__(self):
        return f"{self.file_name} - {self.company} - {self.department}"

    def save(self, *args, **kwargs):
        # Set the file name to the original filename
        self.file_name = os.path.basename(self.file.name)

        # Create the company directory if it doesn't exist
        company_dir = f'uploads/company_{self.company_id}'
        os.makedirs(company_dir, exist_ok=True)

        # Create the department directory if it doesn't exist
        department_dir = f'{company_dir}/{self.department}'
        os.makedirs(department_dir, exist_ok=True)

        # Create the year directory if it doesn't exist
        year_dir = f'{department_dir}/{self.year}'
        os.makedirs(year_dir, exist_ok=True)

        # Create the month directory if it doesn't exist
        month_dir = f'{year_dir}/{self.month}'
        os.makedirs(month_dir, exist_ok=True)

        # Create the reportname directory if it doesn't exist
        reportname_dir = f'{month_dir}/{str(self.reports_name)}'
        os.makedirs(reportname_dir, exist_ok=True)

        super().save(*args, **kwargs)

sfcy/company/forms.py
# company/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from .models import Company, WhatsAppNumber, UserCompanyMapping, FileUpload, ReportName, Department, Month, Year, ReportName

class UserCompanyMappingForm(forms.ModelForm):
    class Meta:
        model = UserCompanyMapping
        fields = ['company', 'is_approved']

class CompanyForm(forms.ModelForm):
    whatsapp_number = forms.CharField(max_length=15, required=True)

    class Meta:
        model = Company
        exclude = ['is_approved', 'confirmation_token']

class CompanyMappingForm(forms.Form):
    pan_number = forms.CharField(label='Company PAN Number', max_length=10)

class FileUploadForm(forms.ModelForm):
    department = forms.ModelChoiceField(
        label='Department',
        queryset=Department.objects.all(),  # Set the queryset to get all departments
        widget=forms.Select(attrs={'class': 'form-control'}),
    )
    month = forms.ModelChoiceField(
        label='Month',
        queryset=Month.objects.all(),  # Set the queryset to get all departments
        widget=forms.Select(attrs={'class': 'form-control'}),
    )
    year = forms.ModelChoiceField(
        label='Year',
        queryset=Year.objects.all(),  # Set the queryset to get all departments
        widget=forms.Select(attrs={'class': 'form-control'}),
    )
    reports_name = forms.ModelChoiceField(
        label='Report',
        queryset=ReportName.objects.all(),  # Set the queryset to get all departments
        widget=forms.Select(attrs={'class': 'form-control'}),
    )
    description = forms.CharField(
        label='Remarks',
        widget=forms.TextInput(attrs={'class': 'form-control'}),
    )
    file = forms.FileField(
        widget=forms.ClearableFileInput(attrs={'class': 'form-control', 'accept': 'application/pdf,image/*'}),
    )

    class Meta:
        model = FileUpload
        fields = ['department', 'month', 'year', 'reports_name','description', 'file']

sfcy/company/views.py
# company/views.py
from django.core.mail import EmailMessage
from django.shortcuts import render, redirect, get_object_or_404
from django.views import View
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.template.loader import render_to_string
from django.utils.html import strip_tags
from django.utils.crypto import get_random_string
from .models import Company, WhatsAppNumber, UserCompanyMapping, FileUpload
from .forms import CompanyForm, CompanyMappingForm, FileUploadForm
from django.contrib import messages
from django.urls import reverse
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger

@method_decorator(login_required, name='dispatch')
class CompanyCreateView(View):
    def get(self, request):
        form = CompanyForm()
        return render(request, 'company/company_create.html', {'form': form})

    def post(self, request):
        form = CompanyForm(request.POST)

        if form.is_valid():
            company = form.save(commit=False)


            # Get WhatsApp number from the form

            whatsapp_number = form.cleaned_data['whatsapp_number']

            company.save()

            # Create or get the WhatsappNumber instance and associate it with the company
            whatsapp_number_instance, created = WhatsAppNumber.objects.get_or_create(number=whatsapp_number)
            whatsapp_number_instance.companies.add(company)

            # Create UserCompanyMapping for the authenticated user and the created company
            user_company_mapping = UserCompanyMapping.objects.create(user=request.user, company=company)

            # Generate a verification token for user mapping
            verification_token = get_random_string(length=32)
            user_company_mapping.verification_token = verification_token
            user_company_mapping.save()

            # Send confirmation email to the company owner with user mapping verification link
            verification_link = f"http://www.sfcy.in/company/verify_user_mapping/{user_company_mapping.id}/{verification_token}/"
            subject = 'Company Confirmation'
            print(verification_link)
            message = render_to_string('company/confirmation_email.html', {'company': company, 'verification_link': verification_link})
            #plain_message = strip_tags(message)
            from_email = 'webappbook@gmail.com'  # Update with your email or use a custom sender
            to_email = company.email


            email = EmailMessage(subject, message, from_email, [to_email])
            email.content_subtype = 'html'
            email.send()

            return redirect('account_profile')

        return render(request, 'company/company_create.html', {'form': form})

class VerifyUserMappingView(View):
    def get(self, request, mapping_id, verification_token):
        user_company_mapping = get_object_or_404(UserCompanyMapping, id=mapping_id, verification_token=verification_token)

        # Verify the user mapping
        user_company_mapping.is_user_verified = True
        user_company_mapping.save()

        # Redirect to a success page or display a success message
        return render(request, 'company/user_mapping_verified.html')


def user_mapping(request):
    if request.method == 'POST':
        form = CompanyMappingForm(request.POST)
        if form.is_valid():
            pan_number = form.cleaned_data['pan_number']

            try:
                company = Company.objects.get(pan_number=pan_number)
                if UserCompanyMapping.objects.filter(user=request.user, company=company).exists():
                        messages.warning(request, 'You are already linked to this company.')
                        return redirect('user_mapping')
                else:
                    # Create UserCompanyMapping for the authenticated user
                    user_company_mapping = UserCompanyMapping.objects.create(user=request.user, company=company)

                    # Generate a verification token for user mapping
                    verification_token = get_random_string(length=32)
                    user_company_mapping.verification_token = verification_token
                    user_company_mapping.save()

                    # Send confirmation email to the company owner with user mapping verification link
                    verification_link = f"http://www.sfcy.in/company/verify_user_mapping/{user_company_mapping.id}/{verification_token}/"
                    subject = 'User Confirmation'
                    username = request.user.username
                    message = render_to_string('company/confirmation_email.html', {'company': company, 'verification_link': verification_link, 'subject':subject, 'username':username})

                    from_email = 'webappbook@gmail.com'  # Update with your email or use a custom sender
                    to_email = company.email


                    email = EmailMessage(subject, message, from_email, [to_email])
                    email.content_subtype = 'html'
                    email.send()

                return redirect('account_profile')


            except Company.DoesNotExist:
                messages.error(request, 'Company with this PAN number does not exist.')
                return redirect('user_mapping')


    else:
        form = CompanyMappingForm()

    return render(request, 'company/user_mapping.html', {'form': form})

def company_dashboard(request, company_id):
    # Get the company based on the provided company_id
    company = get_object_or_404(Company, id=company_id)

    # Check if the user is a staff member
    if request.user.is_staff:
        # If user is staff, allow access without checking user_mapping
        pass
    else:
        user_mapping = UserCompanyMapping.objects.filter(user=request.user, company=company, is_user_verified=True, is_approved=True).first()
        if user_mapping is None:
            # Redirect to another page or display an error message
            return redirect('access_denied')

    # Pass relevant data to the template
    context = {
        'company': company,
    }

    return render(request, 'company/company_dashboard.html', context)

class CompanyFilesView(View):
    template_name = 'company/company_files.html'
    form_class = FileUploadForm
    items_per_page = 9

    def get(self, request, company_id):
        # Get the company data based on company_id
        company = get_object_or_404(Company, id=company_id)

        # Retrieve files associated with the company
        files = FileUpload.objects.filter(company=company).order_by('-id')

        # Paginate the files
        paginator = Paginator(files, self.items_per_page)
        page = request.GET.get('page')

        try:
            files = paginator.page(page)
        except PageNotAnInteger:
            # If page is not an integer, deliver first page.
            files = paginator.page(1)
        except EmptyPage:
            # If page is out of range (e.g. 9999), deliver last page of results.
            files = paginator.page(paginator.num_pages)

        # Initialize the form for file uploads
        form = self.form_class(initial={'company': company})

        context = {'company': company, 'files':files, 'form':form}
        return render(request, self.template_name, context)

    def post(self, request, company_id):
        # Get the company data based on company_id
        company = get_object_or_404(Company, id=company_id)

        # Retrieve files associated with the company
        files = FileUpload.objects.filter(company=company)

        # Handle file upload
        form = self.form_class(request.POST, request.FILES, initial={'company': company})

        if form.is_valid():
            instance = form.save(commit=False)
            instance.user = request.user
            instance.company = company  # Set the company for the uploaded file
            instance.save()

            messages.success(request, 'File uploaded successfully.')
            return redirect('company_files', company_id=company.id)

        # If the form is not valid, re-render the page with the form and files
        context = {'company': company, 'files': files, 'form': form}
        return render(request, self.template_name, context)


def access_denied(request):
    return render(request, 'company/access_denied.html')

sfcy/company/templates/company/access_denied.html
{% extends 'account/base.html' %}

{% block content %}
<div class="container mt-5">
  <div class="row justify-content-center">
    <div class="col-md-9">
      <div class="card shadow">
        <div class="card-body">
          <h5 class="card-title bg-danger p-3 text-white text-center mb-4">Access Denied</h5>
          <p class ="text-muted">You are not approved by Company owner / Site Admin</p>
            <p><a href="/accounts/profile/">Back</a></p>         
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

sfcy/company/templates/company/company_create.html
{% extends 'account/base.html' %}

{% block content %}
<div class="container mt-5">
  <div class="row justify-content-center">
    <div class="col-md-8">
      <div class="card shadow">
        <div class="card-body">
          <h5 class="card-title text-center mb-4">Create Company</h5>
          <!-- Messages showed by package -->
          {% if messages %}
          <div class="alert alert-info" role="alert">
            {% for message in messages %}
              {{ message }}
            {% endfor %}
          </div>
          {% endif %}
           <!-- Form error -->
          {% if form.errors %}
            {% for field in form %}
              {% for error in field.errors %}
                <div class="alert alert-danger" role="alert">
                  <strong>{{ error|escape }}</strong>
                </div>
              {% endfor %}
            {% endfor %}
            {% for error in form.non_field_errors %}
              <div class="alert alert-danger" role="alert">
                <strong>{{ error|escape }}</strong>
              </div>
            {% endfor %}
          {% endif %}
          <form method="post" action="{% url 'company_create' %}" class="form-signup">
            {% csrf_token %}

            <div class="form-group mb-4">
                <input type="text" class = "form-control" name="name" placeholder="Company Name" autocomplete="name" maxlength="255" required="" id="id_name">
            </div>

            <div class="form-group mb-4">
                <input type="text" class = "form-control" name="pan_number" placeholder="PAN Number" autocomplete="pan_number" spellcheck="false" data-ms-editor="true" maxlength="10" required="" id="id_pan_number">
            </div>

            <div class="form-group mb-4">
                <input type="text" class = "form-control" name="address" placeholder="Address" autocomplete="address" spellcheck="false" data-ms-editor="true" maxlength="255" required="" id="id_address">
            </div>
            <div class = "row">
                <div class="form-group col-md-6 mb-4">
                    <input type="text" class = "form-control" name="city" placeholder="City" autocomplete="city" spellcheck="false" data-ms-editor="true" maxlength="100" required="" id="id_city">
                </div>
    
                <div class="form-group col-md-6 mb-4">
                    <input type="text" class = "form-control" name="pincode" placeholder="PIN Code" autocomplete="pincode" spellcheck="false" data-ms-editor="true" maxlength="6" required="" id="id_pincode">
                </div>
            </div>
            <div class = "row">
                <div class="form-group col-md-6 mb-4">
                    <input type="email" class = "form-control" name="email" placeholder="Email Address" autocomplete="email" maxlength="320" required="" id="id_email">
                </div>
    
                <div class="form-group col-md-6 mb-4">
                    <input type="text" class = "form-control" name="whatsapp_number" placeholder="Whatsapp Number" autocomplete="whatsapp_number" minlength="10" maxlength="10" required="" id="id_whatsapp_number">
                </div>
            </div>

            <button type="submit" style = "width:100%;" class="btn btn-primary btn-block mt-3">Create</button>
          </form>
          
          <p class="mt-3 text-left">
            <a href="{% url 'account_profile' %}">Back</a>.
          </p>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

sfcy/company/templates/company/company_dashboard.html
{% extends 'account/base.html' %}

{% block content %}
  <!-- Company Dashboard Navbar -->
  <nav class="navbar navbar-expand-lg navbar-dark bg-info">
    <div class="container-fluid">
      <a class="navbar-brand" href="#">{{company.name}}</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav"
              aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav ms-auto ">
          <li class="nav-item">
            <a class="nav-link" href="{% url 'account_profile' %}">Profile</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'company_files' company.id %}">Files</a>
          </li>

          <li class="nav-item">
            <a class="nav-link" href="{% url 'account_logout' %}">Logout</a>
          </li>
        </ul>
      </div>
    </div>
  </nav>

  <!-- Main Content for Company Dashboard -->
  <div class="container mt-3">
    <div class="row">
        <div class="container mt-5">
            <div class="row justify-content-center">
              <div class="col-md-9">
                <div class="card shadow">
                  <div class="card-body">
                    <h5 class="card-title bg-secondary p-3 text-white text-center mb-4">Your dashboard will be shown soon ! </h5>

                  </div>
                </div>
              </div>
            </div>
          </div>
      <main class="col-md-12">
        {% block main_content %}{% endblock %}
      </main>
    </div>
  </div>
{% endblock %}

sfcy/company/templates/company/company_files.html
{% extends 'account/base.html' %}

{% block content %}
<!-- Company Dashboard Navbar -->
<nav class="navbar navbar-expand-lg navbar-dark bg-info">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">{{company.name}}</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav"
            aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav ms-auto ">
        <li class="nav-item">
          <a class="nav-link" href="{% url 'company_dashboard' company.id %}">Dashboard</a>
        </li>

        <li class="nav-item">
          <a class="nav-link" href="{% url 'account_logout' %}">Logout</a>
        </li>
      </ul>
    </div>
  </div>
</nav>
<div class="container mt-5">
  <div class="row justify-content-center">
    <div class="col-lg-4">
      <div class="card shadow">
        <div class="card-body">
          <h5 class="card-title bg-danger p-3 text-white text-center mb-4">Upload File</h5>
          <form method="post" enctype="multipart/form-data">
            {% csrf_token %}

            {{ form.as_p }}
            <button class ="btn btn-primary mt-4 mb-3" style = "width:100%"type="submit">Upload</button>
          </form>
        </div>
      </div>
    </div>

    <div class="col-lg-8 mt-4 mt-lg-0">
      <div class="card shadow">
        <div class="card-body">
          <h5 class="card-title bg-danger p-3 text-white text-center mb-4">Uploaded Files</h5>
          {% if files %}
            <table class="table">
              <thead>
                <tr>
                  <th scope="col">File Name</th>
                  <th scope="col">File</th>
                  <!-- Add more table headers as needed -->
                </tr>
              </thead>
              <tbody>
                {% for file in files %}
                  <tr>
                    <td>{{ file.file_name }}</td>
                    <td><a href="{{ file.file.url }}" target="_blank" class="btn btn-secondary btn-sm" download>Download</a></td>
                    <!-- Add more table data as needed -->
                  </tr>
                {% endfor %}
              </tbody>
            </table>

            {% if files.has_other_pages %}
              <ul class="pagination justify-content-center">
                {% if files.has_previous %}
                  <li class="page-item"><a class="page-link" href="?page=1">&laquo;&laquo;</a></li>
                  <li class="page-item"><a class="page-link" href="?page={{ files.previous_page_number }}">{{ files.previous_page_number }}</a></li>
                {% endif %}
                <li class="page-item disabled"><span class="page-link">{{ files.number }}</span></li>
                {% if files.has_next %}
                  <li class="page-item"><a class="page-link" href="?page={{ files.next_page_number }}">{{ files.next_page_number }}</a></li>
                  <li class="page-item"><a class="page-link" href="?page={{ files.paginator.num_pages }}">&raquo;&raquo;</a></li>
                {% endif %}
              </ul>
            {% endif %}
          {% else %}
            <p>No files have been uploaded yet.</p>
          {% endif %}
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

sfcy/company/templates/company/confirmation_email.html
<!-- templates/company/confirmation_email.html -->
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Company Confirmation</title>
</head>
<body>

    <h2>{{subject}}</h2>
    <hr>
    <p>Dear Client,</p>

    <p>Your company, {{ company.name }}, has been created successfully!</p>

    <p>{{ username }} is requesting you to complete the user mapping process. If you wish to approve this user, you can click the link below; otherwise, ignore it:</p>

    <a href="{{ verification_link }}" target="_blank">Verify User Mapping</a>

    <p>If you did not initiate this action or have any questions, please contact us immediately.</p>

    <p>Thank you for choosing our platform!</p>

    <p>Best regards,<br>
    SF Consultancy</p>

</body>
</html>

sfcy/company/templates/company/user_mapping.html
{% extends 'account/base.html' %}

{% block content %}
<div class="container mt-5">
  <div class="row justify-content-center">
    <div class="col-md-8">
      <div class="card shadow">
        <div class="card-body">
          <h5 class="card-title text-center mb-4">User Mapping</h5>
          <!-- Messages showed by package -->
          {% if messages %}
          <div class="alert alert-info" role="alert">
            {% for message in messages %}
              {{ message }}
            {% endfor %}
          </div>
          {% endif %}
           <!-- Form error -->
          {% if form.errors %}
            {% for field in form %}
              {% for error in field.errors %}
                <div class="alert alert-danger" role="alert">
                  <strong>{{ error|escape }}</strong>
                </div>
              {% endfor %}
            {% endfor %}
            {% for error in form.non_field_errors %}
              <div class="alert alert-danger" role="alert">
                <strong>{{ error|escape }}</strong>
              </div>
            {% endfor %}
          {% endif %}
          <form method="post" action="{% url 'user_mapping' %}" class="form-signup">
            {% csrf_token %}

            

            <div class="form-group mb-4">
                <input type="text" class = "form-control" name="pan_number" placeholder="Company PAN Number" autocomplete="pan_number" spellcheck="false" data-ms-editor="true" maxlength="10" required="" id="id_pan_number">
            </div>

            
            <button type="submit" style = "width:100%;" class="btn btn-primary btn-block mt-3">Create</button>
          </form>
          
          <p class="mt-3 text-left">
            <a href="{% url 'account_profile' %}">Back</a>.
          </p>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

sfcy/company/templates/company/user_mapping_verified.html

{% extends 'account/base.html' %}

{% block content %}
<div class="container mt-5">
  <div class="row justify-content-center">
    <div class="col-md-9">
      <div class="card shadow">
        <div class="card-body">
          <h5 class="card-title bg-warning p-3 text-white text-center mb-4">User Mapping Verified</h5>
          <p class ="text-muted">Congratulations! Your user mapping has been verified successfully.</p>
          <p>Thank you for choosing our platform!</p>
                   
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}